name: manskelab
channels:
  - simpleitk
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8.5
  - simpleitk=2.0.2
  - vtk=9.0.1
  - pyqt=5.12.3
  - pip=20.3.3
  - pydicom=2.1.2
  - jupyterlab=3.0.0
  - matplotlib=3.3.3
  - cmake=3.19.6
  - pillow=8.0.1
  - pip:
    - itk
    - itk-ioscanco
